### ISSUE TITLE
mpyc not documented

### ISSUE THREAD

**Issue by mkarliner** [wendlers/mpfshell#15]
What does it do?

:-)

Mike

**Comment by drawkula** [comment]
`mpyc` is defined in [mp/mpfshell.py lines 597...621](https://github.com/wendlers/mpfshell/blob/master/mp/mpfshell.py#L597-L621).
```
mpfs [/]> help mpyc                                                                                   
mpyc <LOCAL PYTHON FILE>                                                                              
        Compile a Python file into byte-code by using mpy-cross (which needs to be in the path).      
        The compiled file has the same name as the original file but with extension '.mpy'.           
                                                                                                      
mpfs [/]> _
```

Some ports of MicroPython allow loading and execution of those precompiled files.

[mpy-cross](https://github.com/micropython/micropython/tree/master/mpy-cross) is part of the MicroPython source tree.

Maybe relevant too: [http://forum.micropython.org/viewtopic.php?f=3&t=2334&p=13327](http://forum.micropython.org/viewtopic.php?f=3&t=2334&p=13327)

**Comment by mkarliner** [comment]
Thanks.
