### ISSUE TITLE
telnet skip login if no username given 

### ISSUE THREAD

**Issue by mhoffma** [wendlers/mpfshell#21]
if no login name password is given is it possible to just setup your nice connection.  I have a very simple local area telnet server that I would like to work with your tool.  my server works with telnet but your tool is much better in that it has all of the other command stuff for getting and putting files.

diff --git a/mp/contelnet.py b/mp/contelnet.py
index 55c726e..9e328fc 100644
--- a/mp/contelnet.py
+++ b/mp/contelnet.py
@@ -42,6 +42,9 @@ class ConTelnet(ConBase):
             self.read = self.__read3

         self.tn = telnetlib.Telnet(ip)
+        if user=='':
+            self.fifo = deque()
+            return

         if b'Login as:' in self.tn.read_until(b'Login as:', timeout=5.0):
             self.tn.write(bytes(user.encode('ascii')) + b"\r\n")

**Comment by wendlers** [comment]
Merged in the pull request with that changes.
