### ISSUE TITLE
archlinux ...

### ISSUE THREAD

**Issue by SquirrelCZE** [wendlers/mpfshell#3]
Hi,

I am user of archlinux (unfortunetly) and it seems like your app is not python3 compatible, sad thing is that on archlinux 'python' library points to python3... 

would you mind to explicitly use "python2" binary in your 'mpfshell' bash executable?

**Comment by wendlers** [comment]
Good point :-). Done with latest commit. 

I am planning on Python 3 support. If it is import for you, you might open a feature request.

**Comment by wendlers** [comment]
Reverted back to just "python" since now both, Python2 and Python3 are supported.
