### ISSUE TITLE
Request: command line argument to open board directly

### ISSUE THREAD

**Issue by fstengel** [wendlers/mpfshell#34]
Being a lazy person :sweat_smile: I wonder if it would not be possible to use `mpfshell`as follows:
```
mpfshell --open tty.SLAB_USBtoUART
```
or (even quicker)
```
mpfshell tty.SLAB_USBtoUART
```
instead of:
```
mpfshell
mpfs [/]> open tty.SLAB_USBtoUART
```
That way, one could use the shell's history to connect to the board: I tend to forget what `tty.*` my board is connected to... :flushed:

**Comment by fstengel** [comment]
See relevant pull request (#35)...

**Comment by ulno** [comment]
Why don't you just do: ```mpfshell -c "open tty.SLAB_USBtoUART"```

**Comment by fstengel** [comment]
Indeed. However, being lazy, `mpfshell -c "open ..."` seems a bit less efficient than `mpfshell ...` Furthermore, I don't quite see the point in not opening the connection to the board as soon as one interactively uses mpfshell.

**Comment by ulno** [comment]
+1 for using open anyway always as first command -> maybe specifying only one parameter should directly connect to that

Though, maybe this becomes strange when you deal with several boards in one mpfshell script.

**Comment by fstengel** [comment]
Very good point. Up until now, I would have thought that to access more than one board one would have to open them using one instance of `mpfshell` per board.

**Comment by wendlers** [comment]
Feature was added by push request.
