### ISSUE TITLE
ls does not list files created on the esp8266

### ISSUE THREAD

**Issue by craftyguy** [wendlers/mpfshell#36]
Steps to reproduce:

1) in repl/webrepl:
```
>>> with open('app', 'w') as f:
>>>    f.write("hello")
```
2) in mpfshell:
```
mpfs [/]> ls

Remote files in '/':

```

3) in repl/webrepl:
```
>>> import os
>>> os.listdir()
['app']
```
4) in mpfshell:
```
mpfs [/]> cat app
hello
```

**Comment by wendlers** [comment]
Yes, this is due to the fact, that the shell uses caching by default. For now, you could add `--nocache` when calling the shell like so:

    mpfshell --nocache

An other solution would be to invalidate the cache at the moment the we return from REPL to the shell prompt. I will flag this as an enhancement.

**Comment by skorokithakis** [comment]
Fixed, thank you!
