### ISSUE TITLE
pwd without a connection exits

### ISSUE THREAD

**Issue by hosaka** [wendlers/mpfshell#4]
Hey,

If I don't open the serial port and try to use the pwd command (I know I'm not supposed to :)) I get:
```
** Micropython File Shell v0.6, 2016 sw@kaltpost.de ** 

mpfs [/]> pwd
'NoneType' object has no attribute 'pwd'
```
And then I get thrown back into my terminal. Perhaps need a similar message as you have for other commands `Not connected to device. Use 'open' first.`

**Comment by wendlers** [comment]
That's right. I added the mentioned behavior. Thanks for reporting.
