### ISSUE TITLE
can't connect via serial port on windows 

### ISSUE THREAD

**Issue by kromosomX** [wendlers/mpfshell#6]
open COM5 

fails with:

** Micropython File Shell v0.7.0, sw@kaltpost.de **

mpfs [/]> open COM5

Failed to open: ser:/dev/COM5

**Comment by wendlers** [comment]
I totally see the problem, and the fix seams easy. I will try to solve that later today, but I need your help for testing since I don't have a Windows environment.

**Comment by kromosomX** [comment]
I'll be glad to help with any testing.

**Comment by wendlers** [comment]
Windows style port names are now accepted and connected to. Please note that a Windows port name is expected to start with uppercase COM.
