### ISSUE TITLE
Files in subdirectories inaccessible if running mpfshell from Windows

### ISSUE THREAD

**Issue by zouden** [wendlers/mpfshell#71]
On micropython systems with the /flash subdirectory, all get/put commands fail when running mpfshell from Windows. This is caused by the use of `os.path.join` in mpfexp.py which results in file paths joined with \\\\ instead of /. Micropython's file system uses /.

I managed to fix it by `import posixpath` in mpfexp.py followed by replacing all instances of `os.path.join` with `posixpath.join`.

**Comment by skorokithakis** [comment]
Would you care to issue a PR? This shouldn't break existing functionality, right?

**Comment by skorokithakis** [comment]
Hmm, is that module in the standard library?

**Comment by zouden** [comment]
Yep, I'll do a PR. 

It's in the standard library, but I'm not sure if it's the 'best' way of forcing posix-like paths. Some documentation here:
https://docs.python.org/3/library/pathlib.html
