### ISSUE TITLE
How to run scripts

### ISSUE THREAD

**Issue by cecchisandrone** [wendlers/mpfshell#75]
Is it possible to run scripts using mpfshell (like run command in ampy)? 
Thanks.

**Comment by barbudor** [comment]
I don't know ampy but you can use the REPL console (>>>) if this is what you are looking for.

**Comment by skorokithakis** [comment]
That is correct, you can use the REPL and run whatever script is on the microcontroller.

**Comment by cecchisandrone** [comment]
> I don't know ampy but you can use the REPL console (>>>) if this is what you are looking for.

What is the command?

**Comment by barbudor** [comment]
Have you tried to use `?` or`help`commands ?
It's there, hidden in plain sight:
![screenshot 5](https://user-images.githubusercontent.com/2996042/55183941-3ef71a00-5191-11e9-9f3a-1228078f0da3.png)

**Comment by cecchisandrone** [comment]
I mean running a script from repl
Il 28 mar 2019, 19:40 +0100, Barbudor <notifications@github.com>, ha scritto:

**Comment by barbudor** [comment]
Oh. Sorry for the misunderstanding and little moking.
That's not related to mpfshell itself. It would be the same whatever terminal you use (uPyCraft, Mu, ...)
I'm using `import  nameofscript`  (without the .py) but not sure if that's the only way.
Note that `import` is not just exactly 'running'. That's importing and compiling the code and executing the part of the code that is at the root level (outside of any def or class). Which means that you cannot re-import again to re-execute as the module has already been imported.
I suggest you move this question/discussion to MicroPython forum: https://forum.micropython.org/

**Comment by cecchisandrone** [comment]
Normally I do this in ampy (run command). The problem of that shell is that you see the output of the script only when it terminates, so I was trying to find an alternative.
Il 28 mar 2019, 20:10 +0100, Barbudor <notifications@github.com>, ha scritto:

**Comment by skorokithakis** [comment]
Hmm, I'm not entirely sure what you want to do. Do you want to run a script that's on the computer, or on the MPU?

**Comment by cecchisandrone** [comment]
On the MPU.
Il 28 mar 2019, 23:29 +0100, Stavros Korokithakis <notifications@github.com>, ha scritto:
