### ISSUE TITLE
`repl` via ws: uses 100% cpu

### ISSUE THREAD

**Issue by drawkula** [wendlers/mpfshell#9]
Using...
```
** Micropython File Shell v0.7.3, sw@kaltpost.de ** 
-- Running on Python 2.7 using PySerial 3.1 --
```
...`repl` via ws: uses 100% cpu and is slow like typing thru a 300Bd modem.

Leaving `repl` frees cpu usage again.

Happens with:
- MicroPython v1.8.1-54-g23067a1
- MicroPython v1.8.1-77-gc7fba52

**Comment by wendlers** [comment]
Yes, can confirm this. Seams to be a problem in the "conwebsock" adapter.

**Comment by drawkula** [comment]
Perfect!
No more eating 100% CPU and the typing thru a slow modem feeling is gone...
\\\\o   o//   \o/
