### ISSUE TITLE
Mpfshel closes when connecting to esp82 or esp32

### ISSUE THREAD

**Issue by RAMZUG** [wendlers/mpfshell#97]
Esptool and mpfshell were installed on linux mint.

The firmware is deleted and correctly loaded to esp82 and esp32, python 3.8 and pyserial 3.5 are used. When trying to connect to esp82 or esp32 using mpfshell, the connection is established, but the mpfshell closes. The above is repeated regardless of the ESPxx that is used. The firmware has been reinstalled and the card changed (I have tested it on 8 different cards)

Any idea what could be wrong?
![Problema](https://user-images.githubusercontent.com/42783218/106940065-b2033d00-66e6-11eb-80c2-5a54142830d4.png)

**Comment by AltamarMx** [comment]
This only happens with version 0.9.2,
if you roll back to 0.9.1 works well.

**Comment by skorokithakis** [comment]
That's interesting, can someone bisect and find the offending commit?

**Comment by edcline** [comment]
same problem with 0.9.2 on windows -> esp32
this is my first install - how do you do a 'roll back' to 0.9.1.   I have googled it but it is not clear and I am new to python/pip...
Thank You

**Comment by AltamarMx** [comment]
uninstall first
pip uninstall mpfshell
reinstall specifying version
pip install mpfshell==0.9.1
pip or pip3, whetever you are using.
